# Generated by Django 2.1.2 on 2018-10-09 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='paulkottalil20@gmail.com', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='paulkottalil20@gmail.com', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 20, 10, 12, 984478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6ccd22c1-0cd9-4890-9824-f59ee1d89646'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e194f392-d58d-47a2-833e-67e97ba6fd73'), editable=False, primary_key=True, serialize=False),
        ),
    ]
